### ISSUE TITLE
Error on launchers example: "No module named 'plugins.image'"

### ISSUE THREAD

**Issue by ViktorNova** [maandree/xpybar#2]
Hi, I installed this through AUR and am getting "ImportError: No module named 'plugins.image'" when using the launchers example config.

**Comment by maandree** [comment]
Everything should be in order now. graphicsmagick as been added as a dependency because of a regression in imagemagick, but imagemagick is still needed because of deficiencies in graphicsmagick, so now imagemagick, graphicsmagick, librsvg, and file is required.
